config/routes.rb
Rails.application.routes.draw do

  root controller: :static_pages, action: :home

	resources :vim_commands
	resources :blogs
	resources :hash_tags

	get 'static_pages/login'

  get '/google6fa08eaf7749d52b.html',
    to: proc { |env| [200, {}, ["google-site-verification: google6fa08eaf7749d52b.html"]] }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/blog.rb
class Blog < ApplicationRecord
	has_many :taggings
	has_many :hash_tags, through: :taggings
	accepts_nested_attributes_for :hash_tags
end

app/models/hash_tag.rb
class HashTag < ApplicationRecord
	# has_many :taggings
	has_many :taggings, :dependent => :destroy
	has_many :blogs, through: :taggings
end

app/models/sale.rb
class Sale < ApplicationRecord
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :blog
  belongs_to :hash_tag
end

app/models/vim_command.rb
class VimCommand < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

	protected
		def authenticate
			authenticate_or_request_with_http_basic do |username, password|
				username == USER_ID && password == PASSWORD
				if(username == USER_ID && password == PASSWORD) 
					session[:logged_in] = true
				else
					session[:logged_in] = false
					redirect_to root_path
				end
			end
		end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

	def index
		@blogs = Blog.all
	end

	def show
		@blog = Blog.find(params[:id])
		@hash_tags = @blog.hash_tags.in_groups(3)
	end

	def new
		@blog = Blog.new
	end

	def create
		@blog = Blog.new(blog_params)
		@hash_tags = params["blog"]["hash_tags"].split(",")
		@hash_tags.each do |hash_tag|
			if HashTag.where(name: hash_tag).count != 0
				@blog.hash_tags << HashTag.where(name: hash_tag)
			else
				@blog.hash_tags << HashTag.new(name: hash_tag)
			end
		end
		if @blog.save
			redirect_to :action => 'index'
		else
			render :action => 'new'
		end
	end

	def edit
		@blog = Blog.find(params[:id])
	end

	def update
		@blog = Blog.find(params[:id])
		@hash_tag_ids = params["blog"]["hash_tag_ids"]
		@blog.update(title: params[:blog][:title], post: params[:blog][:post])
		redirect_to :action => 'index'
	end

	def destroy
		@blog = Blog.find(params[:id])
		@blog.hash_tags.destroy_all
		@blog.destroy
		redirect_to root
		# Blog.destroy(params[:id])
		# redirect_to blogs_path
	end

	private
		
		def blog_params
			params.require(:blog).permit(:title, :post)
		end

end

app/controllers/concerns/http_auth_concern.rb
module HttpAuthConcern
	extend ActiveSupport::Concern

	included do
		before_action :http_authenticate
	end

	def http_authenticate
		return true unless Rails.env == "production"

		authenticate_or_request_with_http_basic do |username, password|
			username == 'username' && password == 'password'
		end
	end

end

app/controllers/hash_tags_controller.rb
class HashTagsController < ApplicationController
	require 'json'

	def index
		@hash_tags = HashTag.all
		@json_hash_tags = {}
	 	@hash_tags.each do |h_t|
			@json_hash_tags[h_t.name] = h_t.blogs.all.count
		end	
	end

	def show
		@hash_tag = HashTag.find(params["id"])
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_filter :authenticate, :only => :login

  def home
  end

	def login
		redirect_to root_path
	end

end

app/controllers/vim_commands_controller.rb
class VimCommandsController < ApplicationController
	require 'socket'
	require 'resolv-replace'

	before_filter :authenticate, :except => [:index]
	before_action :getIpAddr
	
	def index
		if params[:commit] == "Search"
			@vim_commands = VimCommand.where("LOWER(description) like ?", "%#{params[:search.downcase]}%")
		else
			@vim_commands = VimCommand.all
		end
	end

=begin
	def show
		# @vim_command = VimCommand.find(params[:id])
	end
=end

	def new
		@vim_command = VimCommand.new
	end

	def create
		@vim_command = VimCommand.new(vim_commands_params)
		if @vim_command.save
			redirect_to vim_commands_path
		else
			render 'new'
		end
	end

	def edit
		@vim_command = VimCommand.find(params[:id])
	end

	def update
		@vim_command = VimCommand.find(params[:id])
		if @vim_command.update_attributes(vim_commands_params)
			redirect_to vim_commands_path
		else 
			render 'edit'
		end
	end

	def destroy
		VimCommand.find(params[:id]).destroy
		redirect_to vim_commands_path
	end

	private 

		def vim_commands_params
			params.require(:vim_command).permit(:description, :img_example, :command, :img_example_before)
		end

		def getIpAddr
			@ip = Socket.ip_address_list.detect{|intf| intf.ipv4_private?}
			@ipAddr = @ip.ip_address
		end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def logged_in?
		return session[:logged_in]
	end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/hash_tags_helper.rb
module HashTagsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/vim_commands_helper.rb
module VimCommandsHelper
end

app/views/blogs/edit.html.erb
<h3 class="new_blog_post_header">Edit Blog Post</h3>

<div class="outer_new_blog_post_container">

	<div class="container new_blog_post">

		<%= form_for(@blog, :html => { :class => "new_blog_post_form" }) do |f| %>

      <div style="width: 100%;">
        <div style="width: 28%; float: left; text-align: right; padding-right: 10px;">
          <%= f.label :title %><br>
          <%= f.label :post %><br>
          <%= f.label :hash_tags %><br>
        </div>

        <div style="width: 72%; float: right; text-align: left;">
          <%= f.text_field :title, { :onInput => "title_on_input(this)" } %><br>
          <%= f.text_area :post, { :onChange => "expand_textarea()", :onInput => "edit_on_input(this)", :onKeyUp => "on_key_stroke(this)" } %><br>
					<%= f.collection_check_boxes :hash_tag_ids, @blog.hash_tags, :id, :name %>
          <%= f.submit "Submit", class: "btn new_blog_post_submit" %>
        </div>
      </div>

			<!--div id="wrapper"> 
				<div id="first">
					<div style="width: 28%; float: left; text-align: right; padding-right: 10px;">
						<= f.label :title %><br>
						<= f.label :hash_tags %><br>
					</div>

					<div style="width: 72%; float: right; text-align: left;">
						<= f.text_field :title, { :onInput => "title_on_input(this)" } %><br>
						<= f.collection_check_boxes :hash_tag_ids, @blog.hash_tags, :id, :name %>
					</div>
				</div>
				<div id="second">
          %= f.label :post %><br>
          %= f.text_area :post, { :onChange => "expand_textarea()", :onInput => "edit_on_input(this)", :onKeyUp => "on_key_stroke(this)" } %><br>
				</div>
			</div-->

			<!--div style="width: 100%;">
				<div style="width: 28%; float: left; text-align: right; padding-right: 10px;">
					%= f.label :title %><br>
					%= f.label :post %><br>
				</div>

				<div style="width: 72%; float: right; text-align: left;">
					%= f.text_field :title, { :onInput => "title_on_input(this)" } %><br>
					%= f.text_area :post, { :onKeyUp => "on_key_stroke(this)" } %><br>
					%= f.submit "Submit", class: "btn new_blog_post_submit" %>
				</div>
			</div-->


		<% end %>

	</div>

</div>

app/views/blogs/index.html.erb
<h1 class="page_header">Blog Posts</h1>

<div class="about_div">
	<p class="about">
		&emsp; These are technical blog posts. They cover various topics.
	</p>
</div>

<div class="card-columns">
	<% @blogs.each do |blog| %>
		<div class="card">
			<div class="card-body text-center" onclick="onCardClick(<%= blog.id %>);">
				<h5><%= blog.title %></h5>
				<span style="display: block; width: 200px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">
					<%= blog.post %>
				</span>
				<br>
				<span>
					<% blog.hash_tags.each do |hash_tag| %>
						<%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id) %>
				<% end %>
				</span>
				<!--%= link_to "Show Blog", blog_path(blog.id), :class => "btn btn-light" %-->
			</div>
			<% if logged_in? %>
				<%= link_to "Delete Blog", blog_path(blog.id), method: :delete, data: { conrim: "Are you sure?" }, :class => "btn btn-light" %> 
				<%= link_to "Edit Blog", edit_blog_path(blog.id), :class => "btn btn-light edit_btn" %> 
			<% end %>
		</div>
	<% end %>
</div>

app/views/blogs/logout.html.erb
<h1> You have reached the logout page </h1>

app/views/blogs/show.html.erb
<style>
		.leftbox {
			float: left;
			background: #11ffee00;
			width: 33%;
			/* height: 280px; */
			text-align: center;
			border-right: 5px solid rgba(0, 0, 0, 0.25);
			border-left: 5px solid rgba(0, 0, 0, 0.25);
		}
		.middlebox {
			float: left;
			background: #11ffee00;
			width: 33%;
			/* height: 280px; */
			text-align: center;
			border-right: 5px solid rgba(0, 0, 0, 0.25);
		}
		.rightbox {
			float: right; 
			background: #11ffee00;
			width: 33%;
			/* height: 280px; */
			text-align: center;
			border-right: 5px solid rgba(0, 0, 0, 0.25);
		}	
		.divHashTagBtn { 
			text-shadow: 8px 8px 20px black;
			font-size: 25px;
			/* color: #ffd6ad; */
			color: #f2f2f2; 
			/* font-family: "Courier"; */
			font-family: "Courier New";
			line-height: 2;
		}
		#parent {
			display: flex;
		}
		#narrow {
			width: 200px;
			/* background: #11ffee00; */
			background-color: rgba(112, 112, 112, 0.75);
			text-align: center;
			-moz-box-shadow: inset 0 0 10px rgba(105, 105, 105, 0.85);
			-webkit-box-shadow: inset 0 0 10px rgba(105, 105, 105, 0.85);
			box-shadow: inset 0 0 10px rgba(105, 105, 105, 0.85);
			border: 1px 1px 1px 1px rgba(105, 105, 105, 0.85); 
			border-radius: 5px;
			padding-top: 50px;
		}
		#wide {
			flex: 1;
			background: #11ffee00;
		}
</style>

<h1 class="page_header"><%= @blog.title %></h1>

<br>

<!--div id="wrapper">
	<div id="first">
		<div class="post">
			<span class="post_text">
				%= @blog.post %>
			</span>
		</div>
	</div>

	<div id="second"-->
		<!--span>
			% @hash_tags.each do |hash_tag| %>
				% hash_tag.each do |hash| %>
					%= hash.inspect %><br><br>
				% end %>
			% end %>
			<br><br><br><br>
			% @blog.hash_tags.each do |hash_tag| %>
				%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => "btn btn-light" %>
			% end %-->
			<!--% @blog_array.each do |blog| %>
				%= blog %>
			% end %>
		</span-->
	<!--/div> 
</div-->

<!--div>
	<div class="leftbox">
		% @hash_tags[0].each do |hash_tag| %>
			% if hash_tag != nil %>
				%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => "divHashTagBtn" %> <br>
			% end %>
		% end %>
	</div>

	<div class="middlebox">
		% @hash_tags[1].each do |hash_tag| %>
			% if hash_tag != nil %>
				%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => "divHashTagBtn" %> <br>
			% end %>
		% end %>
	</div>

	<div class="rightbox">
		% @hash_tags[2].each do |hash_tag| %>
			% if hash_tag != nil %>
				%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => "divHashTagBtn" %> <br>
			% end %>
		% end %>
	</div>
</div-->


<div id="parent">
	<div id="wide">    
		<div class="post post_blog_show">
			<span class="post_text">
				<%= @blog.post.html_safe %>
			</span>
		</div>
	</div>

	<div id="narrow">
			<% @blog.hash_tags.each do |hash_tag| %>
				<%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => "divHashTagBtn" %><br>
			<% end %>
	</div>
</div>
<br><br><br>

app/views/hash_tags/copy_index.html.erb
<h1 class="page_header">All Hash Tags</h1>

<!-- https://codepen.io/dannievinther/pen/LaJoaW -->

<style>
p {
	overflow: hidden;
	padding: 1em;
	width: 25em;
  height: 25em;
	border-radius: 50%;
	/* background: #352961; */
	background: rgba(128, 128, 128, 0.85);;
  color: #e6b2c6;
  hyphens: auto;
  font-weight: 300;
  /*text-align: justify;*/
  text-align-last: center;
}

[aria-hidden='true'] {
  display: contents;
}

[aria-hidden='true']:before,
[aria-hidden='true']:after {
  content: "";
  float: left;
  width: 50%;
  height: 100%;
  --bite:
    radial-gradient(
      farthest-side at var(--pos-x, 100%),
      transparent 99%,
      red);
  shape-outside: var(--bite);
}

[aria-hidden='true']:after {
  float: right;
  --pos-x: 0;
}

html,
body {
  height: 100%;
}

body {
  display: grid;
  place-items: center;
}

</style>

<!--p lang="en">
	<span aria-hidden='true'></span>
	Writers write descriptive paragraphs because their purpose is to describe something. Their point is that something is beautiful or disgusting or strangely intriguing. Writers write persuasive and argument paragraphs because their purpose is to persuade or convince someone. Their point is that their reader should see things a particular way and possibly take action on that new way of seeing things. Writers write paragraphs of comparison because the comparison will make their point clear to their readers.
</p-->

<!--% @hash_tags.each do |hash_tag| %>
	%= link_to "#{hash_tag.name}", hash_tag_path(hash_tag.id), :class => "btn btn-light" %>
end %-->

<center>
<p lang="en">
	<span aria-hidden="true"></span>
<% @hash_tags.each do |hash_tag| %>
	<!--%= link_to(hash_tag_path(hash_tag.id)) do %>
			<div class="hash_tag_index_div">
				<span class="hash_tag_link">
					%= hash_tag.name %>
				</span>
				<br>
			  Blog post count: %= hash_tag.blogs.all.count %>
			</div>	
	% end %-->
	<!--a href="#">
		%= hash_tag.name %> 
		<span class="badge">
			%= hash_tag.blogs.all.count %>
		</span>
	</a-->
	<!--%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => 'hash_tag_link' %--> 
	<!--span class="badge"-->
		<% @hashTagCount = hash_tag.blogs.all.count %>
		<% if @hashTagCount == 1 %>
			<%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => 'hash_tag_link hash_tag_link_tier_one' %> 
			<span class="badge" style="font-size: 12px;">
				<%= hash_tag.blogs.all.count %>
			</span>
		<% elsif @hashTagCount == 2 %>
			<%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => 'hash_tag_link hash_tag_link_tier_two' %> 
			<span class="badge" style="font-size: 16px;">
				<%= hash_tag.blogs.all.count %>
			</span>
		<% elsif @hashTagCount == 3 %>
			<%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => 'hash_tag_link hash_tag_link_tier_three' %> 
			<span class="badge" style="font-size: 20px;">
				<%= hash_tag.blogs.all.count %>
			</span>
		<% elsif @hashTagCount == 4 %>
			<%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => 'hash_tag_link hash_tag_link_tier_four' %> 
			<span class="badge" style="font-size: 24px;">
				<%= hash_tag.blogs.all.count %>
			</span>
		<% elsif @hashTagCount == 5 %>
			<%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => 'hash_tag_link hash_tag_link_tier_five' %> 
			<span class="badge" style="font-size: 28px;">
				<%= hash_tag.blogs.all.count %>
			</span>
		<% elsif @hashTagCount == 6 %>
			<%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => 'hash_tag_link hash_tag_link_tier_six' %> 
			<span class="badge" style="font-size: 32px;">
				<%= hash_tag.blogs.all.count %>
			</span>
		<% end %>
	<!--/span-->
	&nbsp;&nbsp;&nbsp;
<% end %>

</p>
</center>

app/views/hash_tags/index.html.erb
<h1 class="page_header">All Hash Tags</h1>

<!-- https://codepen.io/dannievinther/pen/LaJoaW -->

<style>

/* .p-one {
	overflow: hidden;
	padding: 1em;
	width: 25em;
  height: 25em;
	border-radius: 50%;
	// background: #352961; //
	background: rgba(128, 128, 128, 0.85);;
  color: red;
  hyphens: auto;
  font-weight: 300;
  // text-align: justify; //
  text-align-last: center;
}


p {
	overflow: hidden;
	padding: 1em;
	width: 25em;
  height: 25em;
	border-radius: 50%;
	// background: #352961; //
	background: rgba(128, 128, 128, 0.85);;
  color: #e6b2c6;
  hyphens: auto;
  font-weight: 300;
  // text-align: justify; //
  text-align-last: center;
}

[aria-hidden='true'] {
  display: contents;
}

[aria-hidden='true']:before,
[aria-hidden='true']:after {
  content: "";
  float: left;
  width: 50%;
  height: 100%;
  --bite:
    radial-gradient(
      farthest-side at var(--pos-x, 100%),
      transparent 99%,
      red);
  shape-outside: var(--bite);
}

[aria-hidden='true']:after {
  float: right;
  --pos-x: 0;
}

html,
body {
  height: 100%;
}

body {
  display: grid;
  place-items: center;
} */

</style>


<center>
		<!--span aria-hidden="true"></span>
			% @hash_tags.each do |hash_tag| %>
					% @hashTagCount = hash_tag.blogs.all.count %>
					% if @hashTagCount == 1 %>
						%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => 'hash_tag_link hash_tag_link_tier_one' %> 
						<p class="p-one" lang="en">
							<span class="badge" style="font-size: 12px;">
								%= hash_tag.blogs.all.count %>
							</span>
						</p>
					% elsif @hashTagCount == 2 %>
						<= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => 'hash_tag_link hash_tag_link_tier_two' %> 
						<p class="p-two" lang="en">
							<span class="badge" style="font-size: 16px;">
								<= hash_tag.blogs.all.count %>
							</span>
						</p>
					% elsif @hashTagCount == 3 %>
						<p class="p-three" lang="en">
							%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => 'hash_tag_link hash_tag_link_tier_three' %> 
							<span class="badge" style="font-size: 20px;">
								%= hash_tag.blogs.all.count %>
							</span>
						</p>
					% elsif @hashTagCount == 4 %>
						<p class="p-four" lang="en">
							%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => 'hash_tag_link hash_tag_link_tier_four' %> 
							<span class="badge" style="font-size: 24px;">
								%= hash_tag.blogs.all.count %>
							</span>
						</p>
					% elsif @hashTagCount == 5 %>
						<p class="p-five" lang="en">
							%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => 'hash_tag_link hash_tag_link_tier_five' %> 
							<span class="badge" style="font-size: 28px;">
								%= hash_tag.blogs.all.count %>
							</span>
						</p>
					% elsif @hashTagCount == 6 %>
						<p class="p-six" lang="en">
							%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => 'hash_tag_link hash_tag_link_tier_six' %> 
							<span class="badge" style="font-size: 32px;">
							%= hash_tag.blogs.all.count %>
						</p>
				</span>
			% end %>
			&nbsp;&nbsp;&nbsp;
		% end %>
	</p>
</center-->




<center>
	<p lang="en">
		<span aria-hidden="true"></span>
			<% @hash_tags.each do |hash_tag| %>
					<% @hashTagCount = hash_tag.blogs.all.count %>
					<% if @hashTagCount == 1 %>
						<%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => 'hash_tag_link hash_tag_link_tier_one' %> 
						<span class="badge" style="font-size: 12px;">
							<%= hash_tag.blogs.all.count %>
						</span>
					<% elsif @hashTagCount == 2 %>
						<%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => 'hash_tag_link hash_tag_link_tier_two' %> 
						<span class="badge" style="font-size: 16px;">
							<%= hash_tag.blogs.all.count %>
						</span>
					<% elsif @hashTagCount == 3 %>
						<%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => 'hash_tag_link hash_tag_link_tier_three' %> 
						<span class="badge" style="font-size: 20px;">
							<%= hash_tag.blogs.all.count %>
						</span>
					<% elsif @hashTagCount == 4 %>
						<%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => 'hash_tag_link hash_tag_link_tier_four' %> 
						<span class="badge" style="font-size: 24px;">
							<%= hash_tag.blogs.all.count %>
						</span>
					<% elsif @hashTagCount == 5 %>
						<%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => 'hash_tag_link hash_tag_link_tier_five' %> 
						<span class="badge" style="font-size: 28px;">
							<%= hash_tag.blogs.all.count %>
						</span>
					<% elsif @hashTagCount == 6 %>
						<%= link_to "##{hash_tag.name}", hash_tag_path(hash_tag.id), :class => 'hash_tag_link hash_tag_link_tier_six' %> 
						<span class="badge" style="font-size: 32px;">
					<%= hash_tag.blogs.all.count %>
				</span>
			<% end %>
			&nbsp;&nbsp;&nbsp;
		<% end %>
	</p>
</center>

app/views/hash_tags/show.html.erb
<h1 class="page_header">#<%= @hash_tag.name %></h1>

<div class="about_div">
	<p class="about">
		&emsp; These are all blog posts related to the hash tag <%= @hash_tag.name %>. This hash tag has a total of <%= @hash_tag.blogs.length %> blog posts.
	</sp>
</div>



<div class="card-columns">
  <% @hash_tag.blogs.each do |blog| %>
    <div class="card">  
      <div class="card-body text-center">
        <h5><%= blog.title %></h5>
        <span style="display: block; width: 200px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">
          <%= blog.post %>
        </span>
        <br>
        <%= link_to "Show Blog", blog_path(blog.id), :class => "btn btn-light" %>  
        <% if logged_in? %>
          <%= link_to "Delete Blog", blog_path(blog.id), method: :delete, data: { conrim: "Are you sure?" }, :class => "btn btn-light" %>  
          <%= link_to "Edit Blog", edit_blog_path(blog.id), :class => "btn btn-light edit_btn" %>  
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Learning Vim</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag('vim_commands.js') %>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
		<script src="https://d3js.org/d3.v6.min.js"></script>
  </head>

	<div class="sidenav">
		<%= link_to 'Home', root_path, method: :get %>
		&nbsp;&nbsp;&nbsp;<%= link_to 'Vim Commands'.html_safe, vim_commands_path, method: :get %>
		<% if logged_in? %>
			&nbsp;&nbsp;&nbsp;<%= link_to 'New Vim Command'.html_safe, new_vim_command_path, method: :get %>
		<% end %>
		&nbsp;&nbsp;&nbsp;<%= link_to 'Blog'.html_safe, blogs_path, method: :get %>
		&nbsp;&nbsp;&nbsp;<%= link_to 'Hash Tag'.html_safe, hash_tags_path, method: :get %>
		<% if logged_in? %>
			&nbsp;&nbsp;&nbsp;<%= link_to "New Blog", new_blog_path, method: :get %>
		<% end %>
		<% if !logged_in? %>
			&nbsp;&nbsp;&nbsp;<%= link_to 'Log In'.html_safe, static_pages_login_path, method: :get %>
		<% end %>

		<%= form_tag(vim_commands_path, method: :get) do %>
			<%= text_field_tag(:search, params[:search], class: 'nav_search', placeholder: 'Enter a topic') %><br>
			<%= submit_tag("Search") %>
		<% end %>
	</div>


	<body>
		<div class="container">
			<%= yield %>
		</div>
		<!--br>%= debug(params) if Rails.env.development? %-->
	</body>


	<div class="footer navbar-fixed-bottom">
	</div>

</html>

app/views/static_pages/home.html.erb
<h1 class="page_header">Home</h1>

<div class="about_div">
	<p class="about">
		<!--&emsp;--> 
		<center>
			Welcome to the home page of Kendra's Tech Blogs and Intro to Basic Vim Commands. Here you can learn basic vim commands that will give you a kick start in your vim learning. You will also be able to read tech blogs written by my learnings on my coding journey.
			<br><br>
			By: Kendra Kuivenhoven
		</center>
	</p>
</div>

app/views/vim_commands/edit.html.erb
edit.html.erb

<center>
	<%= render 'form', vim_command: @vim_command %>
</center>

app/views/vim_commands/index.html.erb
<h1 class="page_header">Vim Commands</h1>


<div class="about_div">
	<p class="about">
		&emsp; Here are some basic vim commands. Hover over the images to see what the
	final result of the vim command will be.
	</p>
</div>

<span style="display: none;" id="vim_ids"><%= @vim_commands.ids %></span>


<div class="container">
	<% @vim_commands.each_with_index do |v_c, index| %>
			<div id="wrapper">
				<% if logged_in? %>
					<div id="left">
				<% end %>
						<span class="vim_command_title"><%= v_c.command %></span>
						<br>
						<span class="vim_description"><%= v_c.description %></span>
				<% if logged_in? %>
					</div>
					<div id="right">
							<%= link_to "Edit", edit_vim_command_path(:id => v_c.id), class: "btn btn-primary" %><br>
					</div>
				<% end %>
			</div>

			<div style="max-width: 75%; overflow: hidden;">
				<%= image_tag("#{v_c.img_example_before}", 
						:onmouseover => "this.src='assets/#{v_c.img_example}'", 
						:onmouseout => "this.src='assets/#{v_c.img_example_before}'", 
						:height => "300", :width => "auto" ) 
				%>
			</div>
			<br><br>
	<% end %>
</div>